<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_profile_model extends CI_Model
{

    public $table = 'user_profile';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db->reconnect();
    }
    
    // check weather the user present in our sysytem or not
    function CheckforUserLogin($arr) {
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->where('email_address', $arr['user_email']);
        $where = "password LIKE BINARY";
        $this->db->where($where, $arr['user_password']);
        $this->db->where('active', '1');
        $query = $this->db->get();
        $list = $query->result();
        if ($query->result()) {
            return $list[0];
        } else {
            return false;
        }
    }
    // get all
    function get_all($where,$start,$pagesize,$orderby)
    {
        // build the query.
        $query = "SELECT * FROM " .$this->table .' '. $where.' '.$orderby." LIMIT ". $start.','. $pagesize;
        $query = $this->db->query($query);
        return $query->result_array();
    }
    
     // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($where = NULL) {
	$query = "SELECT * FROM " .$this->table .' '. $where;
        $query = $this->db->query($query);
        $count = $query->num_rows();
        return $count;
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('full_name', $q);
	$this->db->or_like('phone_number', $q);
	$this->db->or_like('email_address', $q);
	$this->db->or_like('role', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('active', $q);
	$this->db->or_like('deleted', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        $user_id = $this->db->insert_id();
        return $user_id;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        return true;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    //checking for change password
    public function checkpassword($arr)
    {
        //$user_id=$this->session->userdata('user_id');
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->where('id',$arr['id']);
        $query=$this->db->get();
        $result=$query->result();
       return $result;
    }

    //checking for user
    public function checkuser($arr)
    {
        //$user_id=$this->session->userdata('user_id');
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->where('email_address',$arr['email_address']);
        $query=$this->db->get();
        $result=$query->result();
       return $result;
    }

    //upadete user password functionality
    function updateUserPassword($arr){
        $layout_data = array();
        $layout_data['password'] = $arr['password'];
        $this->db->where('id',$arr['id']);
        $this->db->update($this->table,$layout_data);
        return true;
    }

}

/* End of file User_profile_model.php */
/* Location: ./application/models/User_profile_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-14 09:58:24 */
/* http://harviacode.com */